def print_info(saving_path, args, data_pack):
    print()
    print(' ----------------------------------------------------------- ')
    print(' -------------------- Running Information ------------------ ')
    print('              Folder to save: ' + saving_path)
    if args.load_model:
        print('             Model load from: ' + args.model_path)
    print('             Running dataset: RSR2015 ' + args.dev_eval + '_p' + args.part + '_' + args.gender)
    print('                  Batch size: ' + str(args.batch_size))
    print('         Total epochs to run: ' + str(args.epochs))
    print('           Number of Speaker: ' + str(data_pack.num_labels_spk))
    print('         Number of Utterance: ' + str(data_pack.num_labels_utt))
    print('        Start num of Speaker: ' + str(data_pack.STspkid))
    print('      Start num of Utterance: ' + str(data_pack.STuttid))
    print(' Hid dim of shared, spk, utt: ' + str(args.dim_all) + ', ' + str(args.dim_spk) + ', ' + str(args.dim_utt))
    print(' ----------------------------------------------------------- ')